routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BackendController@index')->name('home');
// Route::post('/mediaTmp', 'BackendController@mediaTmp')->name('mediaTmp');

// Route::match(['get', 'post'], 'movies/{movie}/crew', 'MovieController@crew')->name('movies.crew');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::match(['get', 'post'], 'settings', 'BackendController@settings')->name('settings');



Route::resource('cities', 'CityController');

Route::resource('items', 'ItemController');

Route::resource('sizes', 'SizeController');

Route::resource('additions', 'AdditionController');

Route::resource('deliveryprices', 'DeliverypriceController');

Route::resource('orders', 'OrderController');

Route::resource('orderitems', 'OrderitemController');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/init', function () {
    // \Artisan::call('storage:link');
    \Artisan::call('optimize:clear');
    \Artisan::call('migrate');
    return "Cache is cleared";
});

Auth::routes(['verify' => true]);

Route::get('/', function(){
    return redirect(route('backend.home'));
});

// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider', 'facebook|google');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google');

app/Http/Controllers/Backend/AdditionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\AdditionDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateAdditionRequest;
use App\Http\Requests\UpdateAdditionRequest;
use App\Repositories\AdditionRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class AdditionController extends AppBaseController
{
    use Authorizable;
    /** @var  AdditionRepository */
    private $additionRepository;

    public function __construct(AdditionRepository $additionRepo)
    {
        $this->additionRepository = $additionRepo;
    }

    /**
     * Display a listing of the Addition.
     *
     * @param AdditionDataTable $additionDataTable
     * @return Response
     */
    public function index(AdditionDataTable $additionDataTable)
    {
        return $additionDataTable->render('backend.additions.index');
    }

    /**
     * Show the form for creating a new Addition.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.additions.create');
    }

    /**
     * Store a newly created Addition in storage.
     *
     * @param CreateAdditionRequest $request
     *
     * @return Response
     */
    public function store(CreateAdditionRequest $request)
    {
        $input = $request->all();

        $addition = $this->additionRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }

    /**
     * Display the specified Addition.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('models/additions.singular').' '.__('messages.not_found'));

            return redirect(route('backend.additions.index'));
        }

        return view('backend.additions.show')->with('addition', $addition);
    }

    /**
     * Show the form for editing the specified Addition.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        return view('backend.additions.edit')->with('addition', $addition);
    }

    /**
     * Update the specified Addition in storage.
     *
     * @param  int              $id
     * @param UpdateAdditionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAdditionRequest $request)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        $addition = $this->additionRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }

    /**
     * Remove the specified Addition from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        $this->additionRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\AppBaseController;
use App\Models\Item;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;
use Flash;

class BackendController extends AppBaseController
{
    // use Authorizable;
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usersNum = User::count();
        $staffNum = User::whenRole('staff')->count();
        $itemsNum = Item::count();
        $ordersNum = Order::count();
        $orders = Order::orderBy('id', 'desc')->limit(15)->get();
        return view('backend.home', compact('orders', 'usersNum', 'staffNum', 'itemsNum', 'ordersNum'));
    }

    public function mediaTmp(Request $request)
    {
        $request->validate([
            'file' => 'required|image'
        ]);

        $path = storage_path('tmp/uploads');

        if (!file_exists($path)) {
            mkdir($path, 0777, true);
        }

        $file = $request->file('file');

        $name = uniqid() . '_' . trim($file->getClientOriginalName());

        $file->move($path, $name);

        return response()->json([
            'name'          => $name,
            'original_name' => $file->getClientOriginalName(),
        ]);
    }

    public function settings(Request $request)
    {
        if ($request->isMethod('get')) {
            return view('backend.settings');
        }

        if ($request->isMethod('post')) {
            settings()->set($request->all());
            settings()->save();
            Flash::success(__('messages.saved', ['model' => __('site.settings')]));
            return redirect(route('backend.settings'));
        }
    }
}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CityDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCityRequest;
use App\Http\Requests\UpdateCityRequest;
use App\Repositories\CityRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class CityController extends AppBaseController
{
    use Authorizable;
    /** @var  CityRepository */
    private $cityRepository;

    public function __construct(CityRepository $cityRepo)
    {
        $this->cityRepository = $cityRepo;
    }

    /**
     * Display a listing of the City.
     *
     * @param CityDataTable $cityDataTable
     * @return Response
     */
    public function index(CityDataTable $cityDataTable)
    {
        return $cityDataTable->render('backend.cities.index');
    }

    /**
     * Show the form for creating a new City.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.cities.create');
    }

    /**
     * Store a newly created City in storage.
     *
     * @param CreateCityRequest $request
     *
     * @return Response
     */
    public function store(CreateCityRequest $request)
    {
        $input = $request->all();

        $city = $this->cityRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }

    /**
     * Display the specified City.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('models/cities.singular').' '.__('messages.not_found'));

            return redirect(route('backend.cities.index'));
        }

        return view('backend.cities.show')->with('city', $city);
    }

    /**
     * Show the form for editing the specified City.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        return view('backend.cities.edit')->with('city', $city);
    }

    /**
     * Update the specified City in storage.
     *
     * @param  int              $id
     * @param UpdateCityRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCityRequest $request)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        $city = $this->cityRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }

    /**
     * Remove the specified City from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        $this->cityRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }
}

app/Http/Controllers/Backend/DeliverypriceController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\DeliverypriceDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateDeliverypriceRequest;
use App\Http\Requests\UpdateDeliverypriceRequest;
use App\Repositories\DeliverypriceRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class DeliverypriceController extends AppBaseController
{
    use Authorizable;
    /** @var  DeliverypriceRepository */
    private $deliverypriceRepository;

    public function __construct(DeliverypriceRepository $deliverypriceRepo)
    {
        $this->deliverypriceRepository = $deliverypriceRepo;
    }

    /**
     * Display a listing of the Deliveryprice.
     *
     * @param DeliverypriceDataTable $deliverypriceDataTable
     * @return Response
     */
    public function index(DeliverypriceDataTable $deliverypriceDataTable)
    {
        return $deliverypriceDataTable->render('backend.deliveryprices.index');
    }

    /**
     * Show the form for creating a new Deliveryprice.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.deliveryprices.create');
    }

    /**
     * Store a newly created Deliveryprice in storage.
     *
     * @param CreateDeliverypriceRequest $request
     *
     * @return Response
     */
    public function store(CreateDeliverypriceRequest $request)
    {
        $input = $request->all();

        $deliveryprice = $this->deliverypriceRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }

    /**
     * Display the specified Deliveryprice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('models/deliveryprices.singular').' '.__('messages.not_found'));

            return redirect(route('backend.deliveryprices.index'));
        }

        return view('backend.deliveryprices.show')->with('deliveryprice', $deliveryprice);
    }

    /**
     * Show the form for editing the specified Deliveryprice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        return view('backend.deliveryprices.edit')->with('deliveryprice', $deliveryprice);
    }

    /**
     * Update the specified Deliveryprice in storage.
     *
     * @param  int              $id
     * @param UpdateDeliverypriceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDeliverypriceRequest $request)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        $deliveryprice = $this->deliverypriceRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }

    /**
     * Remove the specified Deliveryprice from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        $this->deliverypriceRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }
}

resources/views/backend/sizes/create.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/users.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.sizes.index') }}">@lang('models/sizes.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.add_new')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    @include('adminlte-templates::common.errors')

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!! Form::open(['route' => 'backend.sizes.store']) !!}

                        @include('backend.sizes.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\CreateSizeRequest', 'form')->ignore('.no-validate'); !!}
@endpush

resources/views/backend/sizes/datatables_actions.blade.php
{!! Form::open(['route' => ['backend.sizes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('backend.sizes.show', $id) }}" class='btn btn-outline-primary btn-sm'>
        <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('backend.sizes.edit', $id) }}" class='btn btn-outline-info btn-sm'>
        <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-sm sa-btn-delete',
        'data-item' => $name,
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/backend/sizes/edit.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/sizes.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.sizes.index') }}">@lang('models/sizes.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.edit')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    @include('adminlte-templates::common.errors')

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!! Form::model($size, ['route' => ['backend.sizes.update', $size->id], 'method' => 'patch']) !!}

                        @include('backend.sizes.fields')

                   {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\UpdateSizeRequest', 'form')->ignore('.no-validate'); !!}
@endpush

resources/views/backend/sizes/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/sizes.fields.name').':') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Size Field -->
<div class="form-group col-sm-6">
    {!! Form::label('size', __('models/sizes.fields.size').':') !!}
    {!! Form::text('size', null, ['class' => 'form-control']) !!}
</div>

<!-- Cities Field -->
<div class="form-group col-sm-6">
    {!! Form::label('cities', __('models/cities.plural').':') !!}
    {!! Form::select('cities[]', $cityItems, null, ['class' => 'form-control select2 no-validate', 'multiple' => 'multiple']) !!}
</div>
<div class="clearfix"></div>

<!-- Items Field -->
<div class="form-group col-sm-6">
    {!! Form::label('items', __('models/items.plural').':') !!}
    {!! Form::select('items[]', $itemItems, null, ['class' => 'form-control select2 no-validate', 'multiple' => 'multiple']) !!}
</div>
<div class="clearfix"></div>

<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price', __('models/sizes.fields.price').':') !!}
    {!! Form::number('price', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('backend.sizes.index') }}" class="btn btn-default">@lang('crud.cancel')</a>
</div>

@push('scripts')
<script>
    $(function () {
        $(document).ready(function() {
            //Initialize Select2 Elements
            $('.select2').select2()
        });
    })
</script>
@endpush

resources/views/backend/sizes/index.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/sizes.plural')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item active">@lang('models/sizes.plural')</li>
                </ol>
                <a href="{{ route('backend.sizes.create') }}" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @lang('crud.add_new')</a>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    @include('flash::message')


    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    @include('backend.sizes.table')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/sizes/show.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/sizes.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.sizes.index') }}">@lang('models/sizes.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.detail')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    @include('backend.sizes.show_fields')
                    <a href="{{ route('backend.sizes.index') }}" class="btn btn-default">
                        @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/sizes/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', __('models/sizes.fields.id').':') !!}
    <p>{{ $size->id }}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', __('models/sizes.fields.name').':') !!}
    <p>{{ $size->name }}</p>
</div>

<!-- Size Field -->
<div class="form-group">
    {!! Form::label('size', __('models/sizes.fields.size').':') !!}
    <p>{{ $size->size }}</p>
</div>

<!-- Cities Field -->
<div class="form-group">
    {!! Form::label('city_id', __('models/cities.plural').':') !!}
@empty($size->cities->toArray())
    <p>
        <span class="btn btn-xs fc btn-danger">@lang('site.NoCity')</span>
    </p>
@else
    <p>
        @foreach ($size->cities as $item)
            <span class="btn btn-xs fc btn-primary">{{ $item['name'] }}</span>
        @endforeach
    </p>
@endempty
</div>

<!-- Items Field -->
<div class="form-group">
    {!! Form::label('item_id', __('models/items.plural').':') !!}
@empty($size->items->toArray())
    <p>
        <span class="btn btn-xs fc btn-danger">@lang('site.NoCity')</span>
    </p>
@else
    <p>
        @foreach ($size->items as $item)
            <span class="btn btn-xs fc btn-primary">{{ $item['name'] }}</span>
        @endforeach
    </p>
@endempty
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('price', __('models/sizes.fields.price').':') !!}
    <p>{{ $size->price }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', __('models/sizes.fields.created_at').':') !!}
    <p>{{ $size->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', __('models/sizes.fields.updated_at').':') !!}
    <p>{{ $size->updated_at }}</p>
</div>

resources/views/backend/sizes/table.blade.php
@section('css')
    @include('backend.layouts.datatables_css')
@endsection
<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('scripts')
    @include('backend.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush