routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BackendController@index')->name('home');
// Route::post('/mediaTmp', 'BackendController@mediaTmp')->name('mediaTmp');

// Route::match(['get', 'post'], 'movies/{movie}/crew', 'MovieController@crew')->name('movies.crew');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::match(['get', 'post'], 'settings', 'BackendController@settings')->name('settings');



Route::resource('cities', 'CityController');

Route::resource('items', 'ItemController');

Route::resource('sizes', 'SizeController');

Route::resource('additions', 'AdditionController');

Route::resource('deliveryprices', 'DeliverypriceController');

Route::resource('orders', 'OrderController');

Route::resource('orderitems', 'OrderitemController');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/init', function () {
    // \Artisan::call('storage:link');
    \Artisan::call('optimize:clear');
    \Artisan::call('migrate');
    return "Cache is cleared";
});

Auth::routes(['verify' => true]);

Route::get('/', function(){
    return redirect(route('backend.home'));
});

// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider', 'facebook|google');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google');

app/Http/Controllers/Backend/AdditionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\AdditionDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateAdditionRequest;
use App\Http\Requests\UpdateAdditionRequest;
use App\Repositories\AdditionRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class AdditionController extends AppBaseController
{
    use Authorizable;
    /** @var  AdditionRepository */
    private $additionRepository;

    public function __construct(AdditionRepository $additionRepo)
    {
        $this->additionRepository = $additionRepo;
    }

    /**
     * Display a listing of the Addition.
     *
     * @param AdditionDataTable $additionDataTable
     * @return Response
     */
    public function index(AdditionDataTable $additionDataTable)
    {
        return $additionDataTable->render('backend.additions.index');
    }

    /**
     * Show the form for creating a new Addition.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.additions.create');
    }

    /**
     * Store a newly created Addition in storage.
     *
     * @param CreateAdditionRequest $request
     *
     * @return Response
     */
    public function store(CreateAdditionRequest $request)
    {
        $input = $request->all();

        $addition = $this->additionRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }

    /**
     * Display the specified Addition.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('models/additions.singular').' '.__('messages.not_found'));

            return redirect(route('backend.additions.index'));
        }

        return view('backend.additions.show')->with('addition', $addition);
    }

    /**
     * Show the form for editing the specified Addition.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        return view('backend.additions.edit')->with('addition', $addition);
    }

    /**
     * Update the specified Addition in storage.
     *
     * @param  int              $id
     * @param UpdateAdditionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAdditionRequest $request)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        $addition = $this->additionRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }

    /**
     * Remove the specified Addition from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        $this->additionRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\AppBaseController;
use App\Models\Item;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;
use Flash;

class BackendController extends AppBaseController
{
    // use Authorizable;
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usersNum = User::count();
        $staffNum = User::whenRole('staff')->count();
        $itemsNum = Item::count();
        $ordersNum = Order::count();
        $orders = Order::orderBy('id', 'desc')->limit(15)->get();
        return view('backend.home', compact('orders', 'usersNum', 'staffNum', 'itemsNum', 'ordersNum'));
    }

    public function mediaTmp(Request $request)
    {
        $request->validate([
            'file' => 'required|image'
        ]);

        $path = storage_path('tmp/uploads');

        if (!file_exists($path)) {
            mkdir($path, 0777, true);
        }

        $file = $request->file('file');

        $name = uniqid() . '_' . trim($file->getClientOriginalName());

        $file->move($path, $name);

        return response()->json([
            'name'          => $name,
            'original_name' => $file->getClientOriginalName(),
        ]);
    }

    public function settings(Request $request)
    {
        if ($request->isMethod('get')) {
            return view('backend.settings');
        }

        if ($request->isMethod('post')) {
            settings()->set($request->all());
            settings()->save();
            Flash::success(__('messages.saved', ['model' => __('site.settings')]));
            return redirect(route('backend.settings'));
        }
    }
}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CityDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCityRequest;
use App\Http\Requests\UpdateCityRequest;
use App\Repositories\CityRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class CityController extends AppBaseController
{
    use Authorizable;
    /** @var  CityRepository */
    private $cityRepository;

    public function __construct(CityRepository $cityRepo)
    {
        $this->cityRepository = $cityRepo;
    }

    /**
     * Display a listing of the City.
     *
     * @param CityDataTable $cityDataTable
     * @return Response
     */
    public function index(CityDataTable $cityDataTable)
    {
        return $cityDataTable->render('backend.cities.index');
    }

    /**
     * Show the form for creating a new City.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.cities.create');
    }

    /**
     * Store a newly created City in storage.
     *
     * @param CreateCityRequest $request
     *
     * @return Response
     */
    public function store(CreateCityRequest $request)
    {
        $input = $request->all();

        $city = $this->cityRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }

    /**
     * Display the specified City.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('models/cities.singular').' '.__('messages.not_found'));

            return redirect(route('backend.cities.index'));
        }

        return view('backend.cities.show')->with('city', $city);
    }

    /**
     * Show the form for editing the specified City.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        return view('backend.cities.edit')->with('city', $city);
    }

    /**
     * Update the specified City in storage.
     *
     * @param  int              $id
     * @param UpdateCityRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCityRequest $request)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        $city = $this->cityRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }

    /**
     * Remove the specified City from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        $this->cityRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }
}

app/Http/Controllers/Backend/DeliverypriceController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\DeliverypriceDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateDeliverypriceRequest;
use App\Http\Requests\UpdateDeliverypriceRequest;
use App\Repositories\DeliverypriceRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class DeliverypriceController extends AppBaseController
{
    use Authorizable;
    /** @var  DeliverypriceRepository */
    private $deliverypriceRepository;

    public function __construct(DeliverypriceRepository $deliverypriceRepo)
    {
        $this->deliverypriceRepository = $deliverypriceRepo;
    }

    /**
     * Display a listing of the Deliveryprice.
     *
     * @param DeliverypriceDataTable $deliverypriceDataTable
     * @return Response
     */
    public function index(DeliverypriceDataTable $deliverypriceDataTable)
    {
        return $deliverypriceDataTable->render('backend.deliveryprices.index');
    }

    /**
     * Show the form for creating a new Deliveryprice.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.deliveryprices.create');
    }

    /**
     * Store a newly created Deliveryprice in storage.
     *
     * @param CreateDeliverypriceRequest $request
     *
     * @return Response
     */
    public function store(CreateDeliverypriceRequest $request)
    {
        $input = $request->all();

        $deliveryprice = $this->deliverypriceRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }

    /**
     * Display the specified Deliveryprice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('models/deliveryprices.singular').' '.__('messages.not_found'));

            return redirect(route('backend.deliveryprices.index'));
        }

        return view('backend.deliveryprices.show')->with('deliveryprice', $deliveryprice);
    }

    /**
     * Show the form for editing the specified Deliveryprice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        return view('backend.deliveryprices.edit')->with('deliveryprice', $deliveryprice);
    }

    /**
     * Update the specified Deliveryprice in storage.
     *
     * @param  int              $id
     * @param UpdateDeliverypriceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDeliverypriceRequest $request)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        $deliveryprice = $this->deliverypriceRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }

    /**
     * Remove the specified Deliveryprice from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        $this->deliverypriceRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }
}

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('backend-files') }}/assets/images/favicon.png">
    <title>{{ config('app.name') }}</title>
    <!-- This page CSS -->
    <!-- chartist CSS -->
    <link href="{{ asset('backend-files') }}/assets/node_modules/morrisjs/morris.css" rel="stylesheet">
    <!--Toaster Popup message CSS -->
    <link href="{{ asset('backend-files') }}/assets/node_modules/toast-master/css/jquery.toast.css" rel="stylesheet">
    <!-- Select2 -->
    <link href="{{ asset('backend-files') }}/assets/node_modules/select2/dist/css/select2.min.css" rel="stylesheet">
    <link href="{{ asset('backend-files') }}/assets/node_modules/dropzone-master/dist/dropzone.css" rel="stylesheet">
    <link href="{{ asset('backend-files') }}/assets/node_modules/dropify/dist/css/dropify.min.css" rel="stylesheet">
    <link href="{{ asset('backend-files') }}/assets/node_modules/sweetalert/sweetalert.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ asset('backend-files') }}/dist/css/style.min.css" rel="stylesheet">
    <!-- Dashboard 1 Page CSS -->
    <link href="{{ asset('backend-files') }}/dist/css/pages/dashboard1.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

<style>
    .invalid-feedback{
        z-index: 3;
        position: inherit;
    }
    .dropzone .dz-preview .dz-image img {
        width: 100%;
        height: 100%;
    }
</style>
</head>

<body class="fixed-layout skin-red-dark">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">{{ config('app.name') }} admin</p>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        @include('backend.layouts.header')
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        @include('backend.layouts.sidebar')
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- MAIN CONTENT  -->
                <!-- ============================================================== -->
                @yield('content')
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer">
            © {{ now()->year }} Si HaMaDa
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{{ asset('backend-files') }}/assets/node_modules/jquery/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap popper Core JavaScript -->
    <script src="{{ asset('backend-files') }}/assets/node_modules/popper/popper.min.js"></script>
    <script src="{{ asset('backend-files') }}/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{ asset('backend-files') }}/dist/js/perfect-scrollbar.jquery.min.js"></script>
    <!--Wave Effects -->
    <script src="{{ asset('backend-files') }}/dist/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="{{ asset('backend-files') }}/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="{{ asset('backend-files') }}/dist/js/custom.min.js"></script>
    <!-- ============================================================== -->
    <!-- This page plugins -->
    <!-- ============================================================== -->
    <!--morris JavaScript -->
    <script src="{{ asset('backend-files') }}/assets/node_modules/raphael/raphael-min.js"></script>
    <script src="{{ asset('backend-files') }}/assets/node_modules/morrisjs/morris.min.js"></script>
    <script src="{{ asset('backend-files') }}/assets/node_modules/jquery-sparkline/jquery.sparkline.min.js"></script>
    <!-- Popup message jquery -->
    <script src="{{ asset('backend-files') }}/assets/node_modules/toast-master/js/jquery.toast.js"></script>
    <!-- Chart JS -->
    <script src="{{ asset('backend-files') }}/dist/js/dashboard1.js"></script>
    <script src="{{ asset('backend-files') }}/assets/node_modules/dropzone-master/dist/dropzone.js"></script>
    <script src="{{ asset('backend-files') }}/assets/node_modules/dropify/dist/js/dropify.min.js"></script>
    <script src="{{ asset('backend-files') }}/assets/node_modules/sweetalert/sweetalert.min.js"></script>
    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    <script src="{{ asset('backend-files') }}/assets/node_modules/select2/dist/js/select2.min.js"></script>

    <script>
    $(function () {
        $(document).ready(function() {
            //start

            /* Start Delete Button */
            $('body').on('click', '.sa-btn-delete', function(e){
                e.preventDefault()
                var btnForm = $(this)
                console.log(e)
                swal({
                    title: "@lang('crud.are_you_sure')",
                    text: '@lang("crud.you_will_delete") "' + btnForm.data("item") + '" @lang("crud.record")!',
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "@lang('crud.yes_delete')",
                    cancelButtonText: "@lang('crud.no_delete')",
                    closeOnConfirm: false,
                    closeOnCancel: false
                }, function(isConfirm){
                    if (isConfirm) {
                        swal("@lang('crud.deleted')", "@lang('crud.record_deleted')", "success");
                        btnForm.closest('form').submit()
                        console.log($(this))
                    } else {
                        swal("@lang('crud.cancelled')", "@lang('crud.record_safe')", "error");
                    }
                })
            })
            /* End Delete Button */

            // End
        })
    })
    </script>
    @stack('scripts')
</body>

</html>

resources/views/backend/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/backend/layouts/menu.blade.php
<li class="{{ Request::is('backend/users*') ? 'active' : '' }}">
    <a href="{{ route('backend.users.index') }}"><i class="fa fa-user"></i><span>@lang('models/users.plural')</span></a>
</li>

{{-- <li class="{{ Request::is('backend/tags*') ? 'active' : '' }}">
    <a href="{{ route('backend.tags.index') }}"><i class="fa fa-tags"></i><span>@lang('models/tags.plural')</span></a>
</li>

<li class="{{ Request::is('backend/categories*') ? 'active' : '' }}">
    <a href="{{ route('backend.categories.index') }}"><i class="fa fa-folder"></i><span>@lang('models/categories.plural')</span></a>
</li>

<li class="{{ Request::is('backend/crews*') ? 'active' : '' }}">
    <a href="{{ route('backend.crews.index') }}"><i class="fa fa-users"></i><span>@lang('models/crews.plural')</span></a>
</li>


<li class="{{ Request::is('backend/movies*') ? 'active' : '' }}">
    <a href="{{ route('backend.movies.index') }}"><i class="fa fa-video-camera"></i><span>@lang('models/movies.plural')</span></a>
</li>

<li class="{{ Request::is('backend/movieFiles*') ? 'active' : '' }}">
    <a href="{{ route('backend.movieFiles.index') }}"><i class="fa fa-file-movie-o"></i><span>@lang('models/movie_files.plural')</span></a>
</li>

<li class="{{ Request::is('backend/reviews*') ? 'active' : '' }}">
    <a href="{{ route('backend.reviews.index') }}"><i class="fa fa-star-half-empty"></i><span>@lang('models/reviews.plural')</span></a>
</li>

<li class="{{ Request::is('backend/pages*') ? 'active' : '' }}">
    <a href="{{ route('backend.pages.index') }}"><i class="fa fa-file"></i><span>@lang('models/pages.plural')</span></a>
</li>

<li class="{{ Request::is('backend/subscribers*') ? 'active' : '' }}">
    <a href="{{ route('backend.subscribers.index') }}"><i class="fa fa-flash"></i><span>@lang('models/subscribers.plural')</span></a>
</li> --}}

<li class="{{ Request::is('backend/roles*') ? 'active' : '' }}">
    <a href="{{ route('backend.roles.index') }}"><i class="fa fa-anchor"></i><span>@lang('models/roles.plural')</span></a>
</li>

<li class="{{ Request::is('backend/settings*') ? 'active' : '' }}">
    <a href="{{ route('backend.settings') }}"><i class="fa fa-cog"></i><span>@lang('site.settings')</span></a>
</li>

<li class="{{ Request::is('backend/cities*') ? 'active' : '' }}">
    <a href="{{ route('backend.cities.index') }}"><i class="fa fa-edit"></i><span>@lang('models/cities.plural')</span></a>
</li>

<li class="{{ Request::is('backend/items*') ? 'active' : '' }}">
    <a href="{{ route('backend.items.index') }}"><i class="fa fa-edit"></i><span>@lang('models/items.plural')</span></a>
</li>

<li class="{{ Request::is('backend/sizes*') ? 'active' : '' }}">
    <a href="{{ route('backend.sizes.index') }}"><i class="fa fa-edit"></i><span>@lang('models/sizes.plural')</span></a>
</li>
<li class="{{ Request::is('backend/additions*') ? 'active' : '' }}">
    <a href="{{ route('backend.additions.index') }}"><i class="fa fa-edit"></i><span>@lang('models/additions.plural')</span></a>
</li>

<li class="{{ Request::is('backend/deliveryprices*') ? 'active' : '' }}">
    <a href="{{ route('backend.deliveryprices.index') }}"><i class="fa fa-edit"></i><span>@lang('models/deliveryprices.plural')</span></a>
</li>

<li class="{{ Request::is('backend/orders*') ? 'active' : '' }}">
    <a href="{{ route('backend.orders.index') }}"><i class="fa fa-edit"></i><span>@lang('models/orders.plural')</span></a>
</li>

<li class="{{ Request::is('backend/orderitems*') ? 'active' : '' }}">
    <a href="{{ route('backend.orderitems.index') }}"><i class="fa fa-edit"></i><span>@lang('models/orderitems.plural')</span></a>
</li>

resources/views/backend/layouts/sidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User Profile-->
        <div class="user-profile">
            <div class="user-pro-body">
                {{-- <div><img src="{{ asset('backend-files') }}/assets/images/users/2.jpg" alt="user-img" class="img-circle"></div> --}}
                <div class="dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle u-dropdown link hide-menu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>
                    <div class="dropdown-menu animated flipInY">
                        <!-- text-->
                        <a href="{{ route('backend.users.edit', auth()->id()) }}" class="dropdown-item"><i class="ti-user"></i> My Profile</a>
                        <div class="dropdown-divider"></div>
                        <!-- text-->
                        <div class="dropdown-divider"></div>
                        <!-- text-->
                        <a href="{{ url('/logout') }}" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-power-off"></i> @lang('auth.sign_out')</a>
                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;"> @csrf </form>
                        <!-- text-->
                    </div>
                </div>
            </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                @include('backend.layouts.menu')
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>