routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BackendController@index')->name('home');
// Route::post('/mediaTmp', 'BackendController@mediaTmp')->name('mediaTmp');

// Route::match(['get', 'post'], 'movies/{movie}/crew', 'MovieController@crew')->name('movies.crew');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::match(['get', 'post'], 'settings', 'BackendController@settings')->name('settings');



Route::resource('cities', 'CityController');

Route::resource('items', 'ItemController');

Route::resource('sizes', 'SizeController');

Route::resource('additions', 'AdditionController');

Route::resource('deliveryprices', 'DeliverypriceController');

Route::resource('orders', 'OrderController');

Route::resource('orderitems', 'OrderitemController');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/init', function () {
    // \Artisan::call('storage:link');
    \Artisan::call('optimize:clear');
    \Artisan::call('migrate');
    return "Cache is cleared";
});

Auth::routes(['verify' => true]);

Route::get('/', function(){
    return redirect(route('backend.home'));
});

// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider', 'facebook|google');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google');

app/Http/Controllers/Backend/AdditionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\AdditionDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateAdditionRequest;
use App\Http\Requests\UpdateAdditionRequest;
use App\Repositories\AdditionRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class AdditionController extends AppBaseController
{
    use Authorizable;
    /** @var  AdditionRepository */
    private $additionRepository;

    public function __construct(AdditionRepository $additionRepo)
    {
        $this->additionRepository = $additionRepo;
    }

    /**
     * Display a listing of the Addition.
     *
     * @param AdditionDataTable $additionDataTable
     * @return Response
     */
    public function index(AdditionDataTable $additionDataTable)
    {
        return $additionDataTable->render('backend.additions.index');
    }

    /**
     * Show the form for creating a new Addition.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.additions.create');
    }

    /**
     * Store a newly created Addition in storage.
     *
     * @param CreateAdditionRequest $request
     *
     * @return Response
     */
    public function store(CreateAdditionRequest $request)
    {
        $input = $request->all();

        $addition = $this->additionRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }

    /**
     * Display the specified Addition.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('models/additions.singular').' '.__('messages.not_found'));

            return redirect(route('backend.additions.index'));
        }

        return view('backend.additions.show')->with('addition', $addition);
    }

    /**
     * Show the form for editing the specified Addition.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        return view('backend.additions.edit')->with('addition', $addition);
    }

    /**
     * Update the specified Addition in storage.
     *
     * @param  int              $id
     * @param UpdateAdditionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAdditionRequest $request)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        $addition = $this->additionRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }

    /**
     * Remove the specified Addition from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        $this->additionRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\AppBaseController;
use App\Models\Item;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;
use Flash;

class BackendController extends AppBaseController
{
    // use Authorizable;
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usersNum = User::count();
        $staffNum = User::whenRole('staff')->count();
        $itemsNum = Item::count();
        $ordersNum = Order::count();
        $orders = Order::orderBy('id', 'desc')->limit(15)->get();
        return view('backend.home', compact('orders', 'usersNum', 'staffNum', 'itemsNum', 'ordersNum'));
    }

    public function mediaTmp(Request $request)
    {
        $request->validate([
            'file' => 'required|image'
        ]);

        $path = storage_path('tmp/uploads');

        if (!file_exists($path)) {
            mkdir($path, 0777, true);
        }

        $file = $request->file('file');

        $name = uniqid() . '_' . trim($file->getClientOriginalName());

        $file->move($path, $name);

        return response()->json([
            'name'          => $name,
            'original_name' => $file->getClientOriginalName(),
        ]);
    }

    public function settings(Request $request)
    {
        if ($request->isMethod('get')) {
            return view('backend.settings');
        }

        if ($request->isMethod('post')) {
            settings()->set($request->all());
            settings()->save();
            Flash::success(__('messages.saved', ['model' => __('site.settings')]));
            return redirect(route('backend.settings'));
        }
    }
}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CityDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCityRequest;
use App\Http\Requests\UpdateCityRequest;
use App\Repositories\CityRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class CityController extends AppBaseController
{
    use Authorizable;
    /** @var  CityRepository */
    private $cityRepository;

    public function __construct(CityRepository $cityRepo)
    {
        $this->cityRepository = $cityRepo;
    }

    /**
     * Display a listing of the City.
     *
     * @param CityDataTable $cityDataTable
     * @return Response
     */
    public function index(CityDataTable $cityDataTable)
    {
        return $cityDataTable->render('backend.cities.index');
    }

    /**
     * Show the form for creating a new City.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.cities.create');
    }

    /**
     * Store a newly created City in storage.
     *
     * @param CreateCityRequest $request
     *
     * @return Response
     */
    public function store(CreateCityRequest $request)
    {
        $input = $request->all();

        $city = $this->cityRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }

    /**
     * Display the specified City.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('models/cities.singular').' '.__('messages.not_found'));

            return redirect(route('backend.cities.index'));
        }

        return view('backend.cities.show')->with('city', $city);
    }

    /**
     * Show the form for editing the specified City.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        return view('backend.cities.edit')->with('city', $city);
    }

    /**
     * Update the specified City in storage.
     *
     * @param  int              $id
     * @param UpdateCityRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCityRequest $request)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        $city = $this->cityRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }

    /**
     * Remove the specified City from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        $this->cityRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }
}

app/Http/Controllers/Backend/DeliverypriceController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\DeliverypriceDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateDeliverypriceRequest;
use App\Http\Requests\UpdateDeliverypriceRequest;
use App\Repositories\DeliverypriceRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class DeliverypriceController extends AppBaseController
{
    use Authorizable;
    /** @var  DeliverypriceRepository */
    private $deliverypriceRepository;

    public function __construct(DeliverypriceRepository $deliverypriceRepo)
    {
        $this->deliverypriceRepository = $deliverypriceRepo;
    }

    /**
     * Display a listing of the Deliveryprice.
     *
     * @param DeliverypriceDataTable $deliverypriceDataTable
     * @return Response
     */
    public function index(DeliverypriceDataTable $deliverypriceDataTable)
    {
        return $deliverypriceDataTable->render('backend.deliveryprices.index');
    }

    /**
     * Show the form for creating a new Deliveryprice.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.deliveryprices.create');
    }

    /**
     * Store a newly created Deliveryprice in storage.
     *
     * @param CreateDeliverypriceRequest $request
     *
     * @return Response
     */
    public function store(CreateDeliverypriceRequest $request)
    {
        $input = $request->all();

        $deliveryprice = $this->deliverypriceRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }

    /**
     * Display the specified Deliveryprice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('models/deliveryprices.singular').' '.__('messages.not_found'));

            return redirect(route('backend.deliveryprices.index'));
        }

        return view('backend.deliveryprices.show')->with('deliveryprice', $deliveryprice);
    }

    /**
     * Show the form for editing the specified Deliveryprice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        return view('backend.deliveryprices.edit')->with('deliveryprice', $deliveryprice);
    }

    /**
     * Update the specified Deliveryprice in storage.
     *
     * @param  int              $id
     * @param UpdateDeliverypriceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDeliverypriceRequest $request)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        $deliveryprice = $this->deliverypriceRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }

    /**
     * Remove the specified Deliveryprice from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        $this->deliverypriceRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }
}

resources/views/backend/orders/create.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/users.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.orders.index') }}">@lang('models/orders.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.add_new')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    @include('adminlte-templates::common.errors')

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!! Form::open(['route' => 'backend.orders.store']) !!}

                        @include('backend.orders.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\CreateOrderRequest', 'form')->ignore('.no-validate'); !!}
@endpush

resources/views/backend/orders/datatables_actions.blade.php
{!! Form::open(['route' => ['backend.orders.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('backend.orders.show', $id) }}" class='btn btn-outline-primary btn-sm'>
        <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('backend.orders.edit', $id) }}" class='btn btn-outline-info btn-sm'>
        <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-sm sa-btn-delete',
        'data-item' => $client['name'],
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/backend/orders/edit.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/orders.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.orders.index') }}">@lang('models/orders.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.edit')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    @include('adminlte-templates::common.errors')

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!! Form::model($order, ['route' => ['backend.orders.update', $order->id], 'method' => 'patch']) !!}

                        @include('backend.orders.fields')

                   {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\UpdateOrderRequest', 'form')->ignore('.no-validate'); !!}
@endpush

resources/views/backend/orders/fields.blade.php
<!-- Client Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('client_id', __('models/orders.fields.client_id').':') !!}
    {!! Form::select('client_id', $userItems, null, ['class' => 'form-control']) !!}
</div>

<!-- Staff Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('staff_id', __('models/orders.fields.staff_id').':') !!}
    {!! Form::select('staff_id', $userItems, null, ['class' => 'form-control']) !!}
</div>

<!-- City Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('city_id', __('models/orders.fields.city_id').':') !!}
    {!! Form::select('city_id', $cityItems, null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('address', __('models/orders.fields.address').':') !!}
    {!! Form::textarea('address', null, ['class' => 'form-control']) !!}
</div>

<!-- Payment Field -->
<div class="form-group col-sm-6">
    {!! Form::label('payment', __('models/orders.fields.payment').':') !!}
    {!! Form::text('payment', null, ['class' => 'form-control']) !!}
</div>

<!-- Delivery Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('delivery_price', __('models/orders.fields.delivery_price').':') !!}
    {!! Form::number('delivery_price', null, ['class' => 'form-control']) !!}
</div>

<!-- Day Field -->
<div class="form-group col-sm-6">
    {!! Form::label('day', __('models/orders.fields.day').':') !!}
    {!! Form::date('day', null, ['class' => 'form-control','id'=>'day']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#day').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endpush

<!-- Time Field -->
<div class="form-group col-sm-6">
    {!! Form::label('time', __('models/orders.fields.time').':') !!}
    {!! Form::text('time', null, ['class' => 'form-control']) !!}
</div>

<!-- Statu Field -->
<div class="form-group col-sm-6">
    {!! Form::label('statu', __('models/orders.fields.statu').':') !!}
    {!! Form::text('statu', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('backend.orders.index') }}" class="btn btn-default">@lang('crud.cancel')</a>
</div>

resources/views/backend/orders/index.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/orders.plural')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item active">@lang('models/orders.plural')</li>
                </ol>
                <a href="{{ route('backend.orders.create') }}" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @lang('crud.add_new')</a>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    @include('flash::message')


    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    @include('backend.orders.table')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/orders/show.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/orders.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.orders.index') }}">@lang('models/orders.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.detail')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    @include('backend.orders.show_fields')

                    @include('backend.orders.show_items')

                    <a href="{{ route('backend.orders.edit', $order->id) }}" class="btn btn-primary">
                        @lang('crud.edit')
                    </a>
                    <a href="{{ route('backend.orders.index') }}" class="btn btn-default">
                        @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/orders/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', __('models/orders.fields.id').':') !!}
    <p>{{ $order->id }}</p>
</div>

<!-- Client Id Field -->
<div class="form-group">
    {!! Form::label('client_id', __('models/orders.fields.client_id').':') !!}
    <p>{{ $order->client_id }}</p>
</div>

<!-- Staff Id Field -->
<div class="form-group">
    {!! Form::label('staff_id', __('models/orders.fields.staff_id').':') !!}
    <p>{{ $order->staff_id }}</p>
</div>

<!-- City Id Field -->
<div class="form-group">
    {!! Form::label('city_id', __('models/orders.fields.city_id').':') !!}
    <p>{{ $order->city_id }}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', __('models/orders.fields.address').':') !!}
    <p>{{ $order->address }}</p>
</div>

<!-- Lat Field -->
<div class="form-group">
    {!! Form::label('lat', __('models/orders.fields.lat').':') !!}
    <p>{{ $order->lat }}</p>
</div>

<!-- Long Field -->
<div class="form-group">
    {!! Form::label('long', __('models/orders.fields.long').':') !!}
    <p>{{ $order->long }}</p>
</div>

<!-- Payment Field -->
<div class="form-group">
    {!! Form::label('payment', __('models/orders.fields.payment').':') !!}
    <p>{{ $order->payment }}</p>
</div>

<!-- Delivery Price Field -->
<div class="form-group">
    {!! Form::label('delivery_price', __('models/orders.fields.delivery_price').':') !!}
    <p>{{ $order->delivery_price }}</p>
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('price', __('models/orders.fields.price').':') !!}
    <p>{{ $order->price }}</p>
</div>

<!-- Day Field -->
<div class="form-group">
    {!! Form::label('day', __('models/orders.fields.day').':') !!}
    <p>{{ $order->day }}</p>
</div>

<!-- Time Field -->
<div class="form-group">
    {!! Form::label('time', __('models/orders.fields.time').':') !!}
    <p>{{ $order->time }}</p>
</div>

<!-- Statu Field -->
<div class="form-group">
    {!! Form::label('statu', __('models/orders.fields.statu').':') !!}
    <p>{{ $order->statu }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', __('models/orders.fields.created_at').':') !!}
    <p>{{ $order->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', __('models/orders.fields.updated_at').':') !!}
    <p>{{ $order->updated_at }}</p>
</div>

resources/views/backend/orders/show_items.blade.php
<div class="col-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@lang('models/orderitems.plural') ({{ $order->orderitems->count() }})</h4>
            <h6 class="card-subtitle"></h6>
            <div id="accordion1" role="tablist" aria-multiselectable="true">
                @foreach ($order->orderitems as $orderitem)
                <div class="card m-b-0">
                    <div class="card-header" role="tab" id="headingOne1{{ $orderitem->id }}">
                        <h5 class="mb-0">
                        <a class="link collapsed" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne1{{ $orderitem->id }}" aria-expanded="false" aria-controls="collapseOne">
                            {{ $orderitem->id }}
                        </a>
                        </h5>
                    </div>
                    <div id="collapseOne1{{ $orderitem->id }}" class="collapse" role="tabpanel" aria-labelledby="headingOne1{{ $orderitem->id }}" style="">
                        <div class="card-body">
                            @include('backend.orderitems.show_fields')
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
</div>

resources/views/backend/orders/table.blade.php
@section('css')
    @include('backend.layouts.datatables_css')
@endsection
<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('scripts')
    @include('backend.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush