routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BackendController@index')->name('home');
// Route::post('/mediaTmp', 'BackendController@mediaTmp')->name('mediaTmp');

// Route::match(['get', 'post'], 'movies/{movie}/crew', 'MovieController@crew')->name('movies.crew');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::match(['get', 'post'], 'settings', 'BackendController@settings')->name('settings');



Route::resource('cities', 'CityController');

Route::resource('items', 'ItemController');

Route::resource('sizes', 'SizeController');

Route::resource('additions', 'AdditionController');

Route::resource('deliveryprices', 'DeliverypriceController');

Route::resource('orders', 'OrderController');

Route::resource('orderitems', 'OrderitemController');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/init', function () {
    // \Artisan::call('storage:link');
    \Artisan::call('optimize:clear');
    \Artisan::call('migrate');
    return "Cache is cleared";
});

Auth::routes(['verify' => true]);

Route::get('/', function(){
    return redirect(route('backend.home'));
});

// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider', 'facebook|google');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google');

app/Models/Role.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public $guarded = [];

    public $fillable = [
        'name',
        'display_name',
        'description'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required|regex:/^[a-zA-Z0-9\\s]+$/|unique:roles,name',
        'display_name' => 'required',
        'description' => 'required',
        'permissions' => 'required|array|min:1'
    ];

    public function scopeRoleNot($query, $role_name)
    {
        return $query->whereNotIn('name', (array) $role_name);
    }// end of scopeWhereRoleNot
}

app/Http/Controllers/Backend/AdditionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\AdditionDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateAdditionRequest;
use App\Http\Requests\UpdateAdditionRequest;
use App\Repositories\AdditionRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class AdditionController extends AppBaseController
{
    use Authorizable;
    /** @var  AdditionRepository */
    private $additionRepository;

    public function __construct(AdditionRepository $additionRepo)
    {
        $this->additionRepository = $additionRepo;
    }

    /**
     * Display a listing of the Addition.
     *
     * @param AdditionDataTable $additionDataTable
     * @return Response
     */
    public function index(AdditionDataTable $additionDataTable)
    {
        return $additionDataTable->render('backend.additions.index');
    }

    /**
     * Show the form for creating a new Addition.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.additions.create');
    }

    /**
     * Store a newly created Addition in storage.
     *
     * @param CreateAdditionRequest $request
     *
     * @return Response
     */
    public function store(CreateAdditionRequest $request)
    {
        $input = $request->all();

        $addition = $this->additionRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }

    /**
     * Display the specified Addition.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('models/additions.singular').' '.__('messages.not_found'));

            return redirect(route('backend.additions.index'));
        }

        return view('backend.additions.show')->with('addition', $addition);
    }

    /**
     * Show the form for editing the specified Addition.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        return view('backend.additions.edit')->with('addition', $addition);
    }

    /**
     * Update the specified Addition in storage.
     *
     * @param  int              $id
     * @param UpdateAdditionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAdditionRequest $request)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        $addition = $this->additionRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }

    /**
     * Remove the specified Addition from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $addition = $this->additionRepository->find($id);

        if (empty($addition)) {
            Flash::error(__('messages.not_found', ['model' => __('models/additions.singular')]));

            return redirect(route('backend.additions.index'));
        }

        $this->additionRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/additions.singular')]));

        return redirect(route('backend.additions.index'));
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\AppBaseController;
use App\Models\Item;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;
use Flash;

class BackendController extends AppBaseController
{
    // use Authorizable;
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usersNum = User::count();
        $staffNum = User::whenRole('staff')->count();
        $itemsNum = Item::count();
        $ordersNum = Order::count();
        $orders = Order::orderBy('id', 'desc')->limit(15)->get();
        return view('backend.home', compact('orders', 'usersNum', 'staffNum', 'itemsNum', 'ordersNum'));
    }

    public function mediaTmp(Request $request)
    {
        $request->validate([
            'file' => 'required|image'
        ]);

        $path = storage_path('tmp/uploads');

        if (!file_exists($path)) {
            mkdir($path, 0777, true);
        }

        $file = $request->file('file');

        $name = uniqid() . '_' . trim($file->getClientOriginalName());

        $file->move($path, $name);

        return response()->json([
            'name'          => $name,
            'original_name' => $file->getClientOriginalName(),
        ]);
    }

    public function settings(Request $request)
    {
        if ($request->isMethod('get')) {
            return view('backend.settings');
        }

        if ($request->isMethod('post')) {
            settings()->set($request->all());
            settings()->save();
            Flash::success(__('messages.saved', ['model' => __('site.settings')]));
            return redirect(route('backend.settings'));
        }
    }
}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CityDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCityRequest;
use App\Http\Requests\UpdateCityRequest;
use App\Repositories\CityRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class CityController extends AppBaseController
{
    use Authorizable;
    /** @var  CityRepository */
    private $cityRepository;

    public function __construct(CityRepository $cityRepo)
    {
        $this->cityRepository = $cityRepo;
    }

    /**
     * Display a listing of the City.
     *
     * @param CityDataTable $cityDataTable
     * @return Response
     */
    public function index(CityDataTable $cityDataTable)
    {
        return $cityDataTable->render('backend.cities.index');
    }

    /**
     * Show the form for creating a new City.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.cities.create');
    }

    /**
     * Store a newly created City in storage.
     *
     * @param CreateCityRequest $request
     *
     * @return Response
     */
    public function store(CreateCityRequest $request)
    {
        $input = $request->all();

        $city = $this->cityRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }

    /**
     * Display the specified City.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('models/cities.singular').' '.__('messages.not_found'));

            return redirect(route('backend.cities.index'));
        }

        return view('backend.cities.show')->with('city', $city);
    }

    /**
     * Show the form for editing the specified City.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        return view('backend.cities.edit')->with('city', $city);
    }

    /**
     * Update the specified City in storage.
     *
     * @param  int              $id
     * @param UpdateCityRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCityRequest $request)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        $city = $this->cityRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }

    /**
     * Remove the specified City from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            Flash::error(__('messages.not_found', ['model' => __('models/cities.singular')]));

            return redirect(route('backend.cities.index'));
        }

        $this->cityRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/cities.singular')]));

        return redirect(route('backend.cities.index'));
    }
}

app/Http/Controllers/Backend/DeliverypriceController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\DeliverypriceDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateDeliverypriceRequest;
use App\Http\Requests\UpdateDeliverypriceRequest;
use App\Repositories\DeliverypriceRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use App\Traits\Authorizable;
use Response;

class DeliverypriceController extends AppBaseController
{
    use Authorizable;
    /** @var  DeliverypriceRepository */
    private $deliverypriceRepository;

    public function __construct(DeliverypriceRepository $deliverypriceRepo)
    {
        $this->deliverypriceRepository = $deliverypriceRepo;
    }

    /**
     * Display a listing of the Deliveryprice.
     *
     * @param DeliverypriceDataTable $deliverypriceDataTable
     * @return Response
     */
    public function index(DeliverypriceDataTable $deliverypriceDataTable)
    {
        return $deliverypriceDataTable->render('backend.deliveryprices.index');
    }

    /**
     * Show the form for creating a new Deliveryprice.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.deliveryprices.create');
    }

    /**
     * Store a newly created Deliveryprice in storage.
     *
     * @param CreateDeliverypriceRequest $request
     *
     * @return Response
     */
    public function store(CreateDeliverypriceRequest $request)
    {
        $input = $request->all();

        $deliveryprice = $this->deliverypriceRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }

    /**
     * Display the specified Deliveryprice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('models/deliveryprices.singular').' '.__('messages.not_found'));

            return redirect(route('backend.deliveryprices.index'));
        }

        return view('backend.deliveryprices.show')->with('deliveryprice', $deliveryprice);
    }

    /**
     * Show the form for editing the specified Deliveryprice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        return view('backend.deliveryprices.edit')->with('deliveryprice', $deliveryprice);
    }

    /**
     * Update the specified Deliveryprice in storage.
     *
     * @param  int              $id
     * @param UpdateDeliverypriceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDeliverypriceRequest $request)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        $deliveryprice = $this->deliverypriceRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }

    /**
     * Remove the specified Deliveryprice from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $deliveryprice = $this->deliverypriceRepository->find($id);

        if (empty($deliveryprice)) {
            Flash::error(__('messages.not_found', ['model' => __('models/deliveryprices.singular')]));

            return redirect(route('backend.deliveryprices.index'));
        }

        $this->deliverypriceRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/deliveryprices.singular')]));

        return redirect(route('backend.deliveryprices.index'));
    }
}

resources/views/backend/roles/create.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/roles.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.roles.index') }}">@lang('models/roles.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.add_new')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    @include('adminlte-templates::common.errors')


    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!! Form::open(['route' => 'backend.roles.store']) !!}

                        @include('backend.roles.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\CreateRoleRequest', 'form')->ignore('.no-validate'); !!}
@endpush

resources/views/backend/roles/datatables_actions.blade.php
{!! Form::open(['route' => ['backend.roles.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('backend.roles.show', $id) }}" class='btn btn-outline-primary btn-sm'>
        <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('backend.roles.edit', $id) }}" class='btn btn-outline-info btn-sm'>
        <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-sm sa-btn-delete',
        'data-item' => $name,
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/backend/roles/edit.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/roles.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.roles.index') }}">@lang('models/roles.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.edit')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    @include('adminlte-templates::common.errors')


    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!! Form::model($role, ['route' => ['backend.roles.update', $role->id], 'method' => 'patch']) !!}

                        @include('backend.roles.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\UpdateRoleRequest', 'form')->ignore('.no-validate'); !!}
@endpush

resources/views/backend/roles/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/roles.fields.name').':') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Display Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('display_name', __('models/roles.fields.display_name').':') !!}
    {!! Form::text('display_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', __('models/roles.fields.description').':') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Permissions -->
<div class="form-group">
    <h4>Permissions</h4>
    <table class="table table-hover">
        <thead>
        <tr>
            <th style="width: 5%;">#</th>
            <th style="width: 15%;">Model</th>
            <th>Permissions</th>
        </tr>
        </thead>

        <tbody>

        @php
            $models = ['roles', 'users', 'cities', 'items', 'sizes', 'additions', 'deliveryprices', 'orders', 'orderitems', 'settings', 'profile'];
            $permission_maps = ['create', 'read', 'update', 'delete'];
        @endphp

        @foreach ($models as $index=>$model)
            <tr>
                <td>{{ $index+1 }}</td>
                <td class="text-capitalize">{{ $model }}</td>
                <td>

                    @if (in_array($model, ['settings', 'profile']))
                        @php
                            $permission_maps = ['read', 'update'];
                        @endphp
                    @endif

                    <select name="permissions[]" class="form-control select2 no-validate" multiple>
                        @foreach ($permission_maps as $permission_map)
                            <option
                                value="{{ $permission_map . '_' . $model }}"
                                {{ !empty($role) && $role->hasPermission($permission_map . '_' . $model) ? 'selected' : '' }}
                            >{{ $permission_map }}</option>
                        @endforeach
                    </select>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('backend.roles.index') }}" class="btn btn-default">@lang('crud.cancel')</a>
</div>

@push('scripts')
<script>
    $(function () {
        $(document).ready(function() {
            //Initialize Select2 Elements
            $('.select2').select2()
        });
    })
</script>
@endpush

resources/views/backend/roles/index.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/roles.plural')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item active">@lang('models/roles.plural')</li>
                </ol>
                <a href="{{ route('backend.roles.create') }}" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @lang('crud.add_new')</a>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    @include('flash::message')

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    @include('backend.roles.table')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/roles/show.blade.php
@extends('backend.layouts.app')

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">@lang('models/roles.singular')</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">@lang('site.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('backend.roles.index') }}">@lang('models/roles.singular')</a></li>
                    <li class="breadcrumb-item active">@lang('crud.detail')</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    @include('backend.roles.show_fields')
                    <a href="{{ route('backend.roles.index') }}" class="btn btn-default">
                        @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/roles/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', __('models/roles.fields.id').':') !!}
    <p>{{ $role->id }}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', __('models/roles.fields.name').':') !!}
    <p>{{ $role->name }}</p>
</div>

<!-- Display Name Field -->
<div class="form-group">
    {!! Form::label('display_name', __('models/roles.fields.display_name').':') !!}
    <p>{{ $role->display_name }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', __('models/roles.fields.description').':') !!}
    <p>{{ $role->description }}</p>
</div>

<!-- Permissions Field -->
<div class="form-group">
    {!! Form::label('description', __('models/roles.fields.description').':') !!}
    <p>
        @foreach ($role->permissions as $item)
            <span class="btn btn-sm fc btn-primary m-1">{{ $item['name'] }}</span>
        @endforeach
    </p>
</div>

resources/views/backend/roles/table.blade.php
@section('css')
    @include('backend.layouts.datatables_css')
@endsection
<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('scripts')
    @include('backend.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush